Repository weakteam/vicly_back, pull requests merged in 2020-03, with the labels that each got.

#1 dependency refactoring
  .scalafmt.conf
  build.sbt
  compiler.sbt
  new/src/main/scala/Main.scala
  project/Dependencies.scala
  project/plugins.sbt
Labels: enhancement

#7 added config & docker-compose
  Dockerfile.back
  Dockerfile.docs
  build.sbt
  docker-compose.yml
  new/src/main/resources/application.conf
  new/src/main/resources/scheme.sql
  new/src/main/scala/config/AppConfig.scala
  new/src/main/scala/config/Database.scala
  new/src/main/scala/config/Flyway.scala
  project/Dependencies.scala
Labels: enhancement

#8 Template of modularity
  build.sbt
  compiler.sbt
  new/src/main/scala/Main.scala
  new/src/main/scala/io/github/weakteam/Application.scala
  new/src/main/scala/io/github/weakteam/controller/AttachmentController.scala
  new/src/main/scala/io/github/weakteam/controller/ChatController.scala
  new/src/main/scala/io/github/weakteam/controller/GroupController.scala
  new/src/main/scala/io/github/weakteam/controller/HelloController.scala
  new/src/main/scala/io/github/weakteam/controller/InviteController.scala
  new/src/main/scala/io/github/weakteam/controller/MessageController.scala
  new/src/main/scala/io/github/weakteam/controller/RoleController.scala
  new/src/main/scala/io/github/weakteam/controller/UserController.scala
  new/src/main/scala/io/github/weakteam/util/http4s/ResponseOps.scala
  new/src/main/scala/io/github/weakteam/util/http4s/implicits.scala
  project/Dependencies.scala
Labels: enhancement

#16 Version route and BuildInfo plugin setup
  build.sbt
  new/src/main/scala/io/github/weakteam/Application.scala
  new/src/main/scala/io/github/weakteam/controller/HelloController.scala
  new/src/main/scala/io/github/weakteam/controller/UserController.scala
  new/src/main/scala/io/github/weakteam/controller/VersionController.scala
  new/src/main/scala/io/github/weakteam/util/http4s/ResponseOps.scala
  project/BuildInfo.scala
  project/Keys.scala
  project/plugins.sbt
Labels: documentation, enhancement

#15 #11 moved entities to new application
  new/src/main/scala/model/Attachment.scala
  new/src/main/scala/model/Chat.scala
  new/src/main/scala/model/ChatType.scala
  new/src/main/scala/model/Group.scala
  new/src/main/scala/model/Invite.scala
  new/src/main/scala/model/Message.scala
  new/src/main/scala/model/Role.scala
  new/src/main/scala/model/SeaweedResponse.scala
  new/src/main/scala/model/User.scala
  new/src/main/scala/model/UserChat.scala
Labels: enhancement

#18 added scoverage & move packages #17
  build.sbt
  new/src/main/scala/io/github/weakteam/Application.scala
  new/src/main/scala/io/github/weakteam/config/AppConfig.scala
  new/src/main/scala/io/github/weakteam/config/Database.scala
  new/src/main/scala/io/github/weakteam/config/Flyway.scala
  new/src/main/scala/io/github/weakteam/model/Attachment.scala
  new/src/main/scala/io/github/weakteam/model/Chat.scala
  new/src/main/scala/io/github/weakteam/model/ChatType.scala
  new/src/main/scala/io/github/weakteam/model/Group.scala
  new/src/main/scala/io/github/weakteam/model/Invite.scala
  new/src/main/scala/io/github/weakteam/model/Message.scala
  new/src/main/scala/io/github/weakteam/model/Role.scala
  new/src/main/scala/io/github/weakteam/model/SeaweedResponse.scala
  new/src/main/scala/io/github/weakteam/model/User.scala
  new/src/main/scala/io/github/weakteam/model/UserChat.scala
  new/src/test/scala/io/github/weakteam/model/RoleSpec.scala
  project/BuildInfo.scala
  project/Dependencies.scala
  project/plugins.sbt
Labels: enhancement

#20 Migrate to pureconfig, unify deps
  build.sbt
  new/src/main/resources/application.conf
  new/src/main/scala/io/github/weakteam/Application.scala
  new/src/main/scala/io/github/weakteam/config/AppConfig.scala
  new/src/main/scala/io/github/weakteam/config/Database.scala
  project/Dependencies.scala
Labels: deps_bump, enhancement, refactoring

#21 Action cache
  .github/workflows/basic.yaml
Labels: enhancement, refactoring
