Repository weakteam/vicly_back, pull requests merged in 2020-04, with the labels that each got.

#23 added codecov report
  .github/workflows/basic.yaml
Labels: enhancement

#25 init README.MD
  README.MD
Labels: enhancement

#27 Setup staff #26
  .scalafmt.conf
  build.sbt
  new/src/main/resources/application.conf
  new/src/main/resources/migration/dev/scheme.sql
  new/src/main/scala/io/github/weakteam/Application.scala
  new/src/main/scala/io/github/weakteam/config/AppConfig.scala
  new/src/main/scala/io/github/weakteam/config/Database.scala
  new/src/main/scala/io/github/weakteam/config/Flyway.scala
  new/src/main/scala/io/github/weakteam/controller/RoleController.scala
  new/src/main/scala/io/github/weakteam/database/DbTransactor.scala
  new/src/main/scala/io/github/weakteam/database/Flyway.scala
  new/src/main/scala/io/github/weakteam/model/Attachment.scala
  new/src/main/scala/io/github/weakteam/model/Chat.scala
  new/src/main/scala/io/github/weakteam/model/ChatType.scala
  new/src/main/scala/io/github/weakteam/model/Group.scala
  new/src/main/scala/io/github/weakteam/model/Invite.scala
  new/src/main/scala/io/github/weakteam/model/Message.scala
  new/src/main/scala/io/github/weakteam/model/Role.scala
  new/src/main/scala/io/github/weakteam/model/SeaweedResponse.scala
  new/src/main/scala/io/github/weakteam/model/User.scala
  new/src/main/scala/io/github/weakteam/model/UserChat.scala
  new/src/main/scala/io/github/weakteam/repository/RoleRepository.scala
  new/src/main/scala/io/github/weakteam/service/RoleService.scala
  new/src/test/scala/io/github/weakteam/model/InviteSpec.scala
  new/src/test/scala/io/github/weakteam/model/RoleSpec.scala
  new/src/test/scala/io/github/weakteam/model/UserChatSpec.scala
  project/Dependencies.scala
  project/plugins.sbt
Labels: enhancement

#30 Add CORS and GZip middleware
  new/src/main/resources/application.conf
  new/src/main/scala/io/github/weakteam/Application.scala
  new/src/main/scala/io/github/weakteam/config/AppConfig.scala
Labels: enhancement

#32 #31 Use refined for config reader
  new/src/main/scala/io/github/weakteam/Application.scala
  new/src/main/scala/io/github/weakteam/config/AppConfig.scala
  new/src/main/scala/io/github/weakteam/database/DbTransactor.scala
  new/src/main/scala/io/github/weakteam/database/Flyway.scala
  new/src/test/scala/io/github/weakteam/service/RoleServiceSpec.scala
  project/Dependencies.scala
Labels: enhancement

#35 Fix the config #34
  new/src/main/resources/application.conf
  new/src/main/resources/migration/dev/V1.0__scheme.sql
  new/src/main/resources/migration/dev/scheme.sql
  new/src/main/scala/io/github/weakteam/Application.scala
  new/src/main/scala/io/github/weakteam/config/AppConfig.scala
  new/src/main/scala/io/github/weakteam/service/RoleService.scala
  new/src/main/scala/io/github/weakteam/util/tofu/logging/implicits.scala
  new/src/test/scala/io/github/weakteam/service/RoleServiceSpec.scala
  new/src/test/scala/io/github/weakteam/util/tofu/logging/ImplicitsSpec.scala
  project/Dependencies.scala
Labels: bug, enhancement

#40 Route/Controller layer
  new/src/main/scala/io/github/weakteam/Application.scala
  new/src/main/scala/io/github/weakteam/controller/RoleController.scala
  new/src/main/scala/io/github/weakteam/route/AttachmentRoutes.scala
  new/src/main/scala/io/github/weakteam/route/ChatRoutes.scala
  new/src/main/scala/io/github/weakteam/route/GroupRoutes.scala
  new/src/main/scala/io/github/weakteam/route/InviteRoutes.scala
  new/src/main/scala/io/github/weakteam/route/MessageRoutes.scala
  new/src/main/scala/io/github/weakteam/route/RoleRoutes.scala
  new/src/main/scala/io/github/weakteam/route/UserRoutes.scala
  new/src/main/scala/io/github/weakteam/route/VersionRoutes.scala
  new/src/main/scala/io/github/weakteam/util/http4s/Typed.scala
  new/src/test/scala/io/github/weakteam/route/RoleRoutesSpec.scala
Labels: arch, enhancement

#37 Role routes
  new/src/main/scala/io/github/weakteam/controller/RoleController.scala
  new/src/main/scala/io/github/weakteam/model/Role.scala
  new/src/main/scala/io/github/weakteam/repository/RoleRepository.scala
  new/src/main/scala/io/github/weakteam/route/RoleRoutes.scala
  new/src/main/scala/io/github/weakteam/service/RoleService.scala
  new/src/main/scala/io/github/weakteam/util/Typed.scala
  new/src/main/scala/io/github/weakteam/util/http4s/Typed.scala
  new/src/test/scala/io/github/weakteam/controller/RoleControllerSpec.scala
  new/src/test/scala/io/github/weakteam/model/RoleSpec.scala
  new/src/test/scala/io/github/weakteam/route/RoleRoutesSpec.scala
Labels: arch, enhancement, test

#43 Rework models
  compiler.sbt
  new/src/main/scala/io/github/weakteam/controller/RoleController.scala
  new/src/main/scala/io/github/weakteam/model/Attachment.scala
  new/src/main/scala/io/github/weakteam/model/Chat.scala
  new/src/main/scala/io/github/weakteam/model/ChatType.scala
  new/src/main/scala/io/github/weakteam/model/Group.scala
  new/src/main/scala/io/github/weakteam/model/Invite.scala
  new/src/main/scala/io/github/weakteam/model/Message.scala
  new/src/main/scala/io/github/weakteam/model/Role.scala
  new/src/main/scala/io/github/weakteam/model/SeaweedResponse.scala
  new/src/main/scala/io/github/weakteam/model/User.scala
  new/src/main/scala/io/github/weakteam/model/UserChat.scala
  new/src/main/scala/io/github/weakteam/model/WithId.scala
  new/src/main/scala/io/github/weakteam/repository/RoleRepository.scala
  new/src/main/scala/io/github/weakteam/service/RoleService.scala
  new/src/main/scala/io/github/weakteam/util/Typed.scala
  new/src/main/scala/io/github/weakteam/util/circe/syntax.scala
  new/src/main/scala/io/github/weakteam/util/http4s/Typed.scala
  new/src/main/scala/io/github/weakteam/util/refined/implicits.scala
  new/src/main/scala/io/github/weakteam/util/tofu/logging/implicits.scala
  new/src/test/scala/io/github/weakteam/controller/RoleControllerSpec.scala
  new/src/test/scala/io/github/weakteam/model/InviteSpec.scala
  new/src/test/scala/io/github/weakteam/model/RoleSpec.scala
  new/src/test/scala/io/github/weakteam/model/UserChatSpec.scala
  project/Keys.scala
Labels: arch, enhancement

#45 Add codeowners
  CODEOWNERS
Labels: enhancement
